import streamlit as st
import torch
import torch.nn as nn
from torchvision import models, transforms
from PIL import Image
import numpy as np
import io
import datetime
import uuid
from fpdf import FPDF

st.set_page_config(page_title="SafeBite Food Safety Inspector", page_icon="🛡️", layout="centered")

FRESHNESS = ["Fit for Consumption (Safe)", "Unfit for Consumption (Spoiled / Risk Detected)"]

class MultiTaskFoodModel(nn.Module):
    def __init__(self, num_cuisines=7, num_freshness=2):
        super().__init__()
        self.backbone = models.mobilenet_v3_small(weights=None)
        in_features = self.backbone.classifier[0].in_features
        self.backbone.classifier = nn.Identity()
        self.cuisine_head = nn.Linear(in_features, num_cuisines)
        self.freshness_head = nn.Linear(in_features, num_freshness)

    def forward(self, x):
        features = self.backbone(x)
        return self.cuisine_head(features), self.freshness_head(features)

@st.cache_resource
def load_model():
    model = MultiTaskFoodModel()
    try:
        model.load_state_dict(torch.load("multitask_food_weights.pth", map_location="cpu"))
    except Exception:
        pass
    model.eval()
    return model

model = load_model()

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

def generate_pdf_report(audit_id, timestamp, verdict_str, conf_score, is_fit, image_pil):
    pdf = FPDF()
    pdf.add_page()
    
    # Title Header Banner
    pdf.set_fill_color(15, 23, 42)
    pdf.rect(0, 0, 210, 32, 'F')
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 14, "FOOD QUALITY & HYGIENE AUDIT REPORT", align="C", ln=True)
    pdf.set_font("Helvetica", size=10)
    pdf.cell(0, 6, "Automated Visual & Microbiological Risk Inspection Record", align="C", ln=True)
    
    pdf.ln(10)
    pdf.set_text_color(0, 0, 0)
    
    # Table Metadata
    with pdf.table(col_widths=(45, 145), text_align=("L", "L")) as table:
        r1 = table.row()
        r1.cell("Audit ID:")
        r1.cell(str(audit_id))
        
        r2 = table.row()
        r2.cell("Inspection Timestamp:")
        r2.cell(str(timestamp))
        
        r3 = table.row()
        r3.cell("Freshness Verdict:")
        r3.cell(verdict_str)
        
        r4 = table.row()
        r4.cell("Model Confidence:")
        r4.cell(f"{conf_score:.2f}%")
        
        r5 = table.row()
        r5.cell("Regulatory Status:")
        r5.cell("PASSED (Commercial standard compliant)" if is_fit else "FLAGGED - VIOLATION (Dispose immediately)")

    pdf.ln(6)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Sample Photographic Evidence:", ln=True)
    
    # Embed Sample Image
    img_buf = io.BytesIO()
    image_pil.save(img_buf, format="JPEG")
    img_buf.seek(0)
    pdf.image(img_buf, w=75, x=15)
    
    pdf.set_y(pdf.get_y() + 65)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Audit Findings & Recommendation:", ln=True)
    pdf.set_font("Helvetica", size=10)
    
    if is_fit:
        findings = (
            "1. Visual surface integrity shows no evidence of microbial contamination.\n"
            "2. Coloration and moisture equilibrium are within acceptable thresholds.\n"
            "3. Sample is certified safe for human consumption and commercial sale."
        )
    else:
        findings = (
            "1. Advanced visual degradation, discoloration, or surface oxidation detected.\n"
            "2. Significant risk of microbial colonization or rancidity.\n"
            "3. Immediate segregation and disposal required under hygiene safety norms."
        )
        
    pdf.multi_cell(0, 6, findings)
    
    pdf.ln(8)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 5, "This is an automated report generated by the SafeBite AI Neural Inspection Core.", align="C", ln=True)
    
    return bytes(pdf.output())

# Main Streamlit UI
st.title("🛡️ SafeBite Inspector")
st.caption("Automated Food Quality, Safety & Hygiene Inspection")

camera_input = st.camera_input("Take sample photo")
file_input = st.file_uploader("Or upload an image", type=["jpg", "jpeg", "png"])

img_file = camera_input if camera_input is not None else file_input

if img_file is not None:
    image = Image.open(img_file).convert("RGB")
    st.image(image, caption="Inspected Food Sample", use_container_width=True)

    with st.spinner("Analyzing food sample quality and safety..."):
        tensor_img = transform(image).unsqueeze(0)
        with torch.no_grad():
            _, f_logits = model(tensor_img)
            f_probs = torch.softmax(f_logits, dim=1)[0]
            f_idx = torch.argmax(f_logits, dim=1).item()
            f_pred = FRESHNESS[f_idx]
            f_conf = f_probs[f_idx].item() * 100

    is_fit = (f_idx == 0)
    audit_id = str(uuid.uuid4())[:8].upper()
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")

    st.divider()
    st.subheader("Inspection Verdict")
    st.metric(label="Safety Classification", value="Fit / Safe" if is_fit else "Spoiled / Unfit", delta=f"{f_conf:.1f}% Confidence")

    if is_fit:
        st.success(f"**Passed:** {f_pred}\n\nSurface integrity shows no visible decomposition or contamination.")
    else:
        st.error(f"**Warning:** {f_pred}\n\nMicrobial degradation, surface oxidation, or discoloration detected.")

    # PDF Export Section
    st.divider()
    st.subheader("📄 Official Compliance Report")
    st.write("Generate and download an official documentation record for this audit.")
    
    pdf_bytes = generate_pdf_report(audit_id, timestamp, f_pred, f_conf, is_fit, image)
    
    st.download_button(
        label="📥 Download Official Audit Report (PDF)",
        data=pdf_bytes,
        file_name=f"SafeBite_Audit_{audit_id}.pdf",
        mime="application/pdf",
        use_container_width=True
    )
